const SPEC_NAMES = {
  oc: 'Operating System',
  cover: 'Case',
  cpu: 'Processor',
  gpu: 'Graphics Card',
  ram: 'RAM',
  storage: 'Storage',
  psu: 'Power Supply',
  cooling: 'Cooling',
  memory: 'Memory Type',
  interface: 'Video Outputs',
  ports: 'Max Resolution',
  maks_p: 'Recommended PSU',
  maks: 'Recommended PSU',
  power: 'Power Consumption',
  sensor: 'Sensor',
  buttons: 'Buttons',
  connection: 'Connection',
  battery: 'Battery',
  interface_p: 'Interface',
  weight: 'Weight',
  driver: 'Driver',
  frequency: 'Frequency',
  microphone: 'Microphone',
  cable: 'Cable',
  capacity: 'Capacity',
  type: 'Type',
  cas: 'CAS Latency',
  voltage: 'Voltage',
  rgb: 'RGB Lighting',
  switches: 'Switches',
  backlight: 'Backlight',
  anticost: 'Anti-Ghosting',
  diagonal: 'Diagonal',
  resolution: 'Resolution',
  panel: 'Panel',
  refresh: 'Refresh Rate',
  response: 'Response Time',
  surface: 'Surface',
  size: 'Size',
  base: 'Base',
  cleaning: 'Cleaning',
  compatibility: 'Compatibility',
  rpm: 'RPM',
  cache: 'Cache',
  formfactor: 'Form Factor',
  warranty: 'Warranty',
  certificate: 'Certificate',
  pfc: 'PFC',
  cables: 'Cables',
  protection: 'Protection',
  cores: 'Cores',
  threads: 'Threads',
  turbo: 'Turbo Frequency',
  socket: 'Socket',
  tdp: 'TDP',
  heatpipes: 'Heat Pipes',
  fan: 'Fan',
  noise: 'Noise Level',
  manufacturer: 'Manufacturer',
  country: 'Country',
  chipset: 'Chipset',
  formfactor_mb: 'Motherboard Form Factor',
  ram_installed: 'RAM Modules',
  ram_total: 'Total RAM',
  ram_frequency: 'RAM Frequency',
  timings: 'Timings',
  profile: 'Profile',
  height: 'Height',
  heat_spreader: 'Heat Spreader',
  gpu_memory: 'VRAM',
  memory_type: 'Memory Type',
  clock_base: 'Base Clock',
  clock_boost: 'Boost Clock',
  length: 'Length',
  slots: 'Slots',
  storage_type: 'Storage Type',
  storage_interface: 'Interface',
  storage_speed: 'Read Speed',
  efficiency: 'Efficiency',
  fan_speed: 'Fan Speed',
  depth: 'Depth',
  cooling_type: 'Cooling Type',
  case: 'Case',
  case_rgb: 'Case Lighting',
  case_fans: 'Fans',
  polling: 'Polling Rate',
  battery_type: 'Battery Type',
  surround: 'Surround Sound',
  impedance: 'Impedance',
  sensitivity: 'Sensitivity',
  mic_frequency: 'Mic Frequency',
  keys: 'Keys',
  wrist_rest: 'Wrist Rest',
  thickness: 'Thickness',
  brightness: 'Brightness',
  contrast: 'Contrast',
  color: 'Color Gamut',
  hdr: 'HDR',
  vesa: 'VESA Mount',
  socket_cpu: 'Socket',
  lithography: 'Lithography',
  memory_support: 'Memory Support',
  pci_express: 'PCI Express',
  max_temp: 'Max Temperature',
  integrated_gpu: 'Integrated GPU',
  memory_bandwidth: 'Memory Bandwidth',
  cuda_cores: 'CUDA Cores',
  ray_tracing_cores: 'RT Cores',
  tensor_cores: 'Tensor Cores',
  max_resolution: 'Max Resolution',
  directx: 'DirectX',
  opengl: 'OpenGL',
  width: 'Width',
  material: 'Material',
  bearing: 'Bearing',
  fan_connector: 'Fan Connector',
  airflow: 'Airflow',
  architecture: 'Architecture',
  l2_cache: 'L2 Cache',
  l3_cache: 'L3 Cache',
  max_memory: 'Max Memory',
  memory_channels: 'Memory Channels'
};

const SPEC_NAMES_DETAIL = {
  warranty: 'Manufacturer Warranty',
  manufacturer: 'Manufacturer',
  country: 'Country of Origin',
  oc: 'Operating System',
  cpu: 'Processor Model',
  buttons: 'Core Count',
  threads: 'Thread Count',
  frequency: 'Processor Frequency',
  anticost: 'Boost Frequency',
  socket_cpu: 'Socket',
  cache: 'Cache',
  cover: 'Socket',
  chipset: 'Chipset',
  ram: 'RAM Slots',
  formfactor_mb: 'Motherboard Form Factor',
  memory: 'RAM Type',
  formfactor: 'RAM Form Factor',
  ram_installed: 'RAM Modules',
  ram_total: 'Total RAM',
  ram_frequency: 'RAM Frequency',
  cas: 'CAS Latency',
  voltage: 'Voltage',
  rgb: 'RGB Lighting',
  capacity: 'Capacity',
  timings: 'Timings',
  profile: 'Profile',
  height: 'Module Height',
  heat_spreader: 'Heat Spreader',
  gpu: 'Graphics Card Model',
  type: 'Graphics Card Type',
  gpu_memory: 'VRAM',
  interface: 'Video Outputs',
  memory_type: 'Memory Type',
  ports: 'Max Resolution',
  power: 'Power Consumption',
  clock_base: 'Base Clock',
  clock_boost: 'Boost Clock',
  length: 'Length',
  slots: 'Slots',
  storage: 'Storage',
  storage_type: 'Storage Type',
  storage_interface: 'Interface',
  storage_speed: 'Read Speed',
  rpm: 'RPM',
  noise: 'Noise Level',
  psu: 'Power Supply',
  certificate: 'Certificate',
  pfc: 'PFC',
  cables: 'Cable Type',
  protection: 'Protection',
  efficiency: 'Efficiency',
  fan_speed: 'Fan Speed',
  depth: 'Depth',
  cooling: 'Cooling',
  cooling_type: 'Cooling Type',
  case: 'Case',
  case_rgb: 'Case Lighting',
  case_fans: 'Fans',
  sensor: 'Sensor',
  connection: 'Connection',
  battery: 'Battery',
  weight: 'Weight',
  interface_p: 'Interface',
  polling: 'Polling Rate',
  switches: 'Switches',
  battery_type: 'Battery Type',
  driver: 'Driver',
  microphone: 'Microphone',
  cable: 'Cable',
  surround: 'Surround Sound',
  impedance: 'Impedance',
  sensitivity: 'Sensitivity',
  mic_frequency: 'Mic Frequency',
  backlight: 'Backlight',
  keys: 'Key Count',
  wrist_rest: 'Wrist Rest',
  surface: 'Surface',
  size: 'Size',
  base: 'Base',
  cleaning: 'Cleaning',
  compatibility: 'Compatibility',
  thickness: 'Thickness',
  diagonal: 'Diagonal',
  resolution: 'Resolution',
  panel: 'Panel',
  refresh: 'Refresh Rate',
  response: 'Response Time',
  brightness: 'Brightness',
  contrast: 'Contrast',
  color: 'Color Gamut',
  hdr: 'HDR',
  vesa: 'VESA Mount',
  cores: 'Core Count',
  turbo: 'Turbo Frequency',
  socket: 'Socket',
  tdp: 'TDP',
  heatpipes: 'Heat Pipes',
  fan: 'Fan',
  lithography: 'Lithography',
  memory_support: 'Memory Support',
  pci_express: 'PCI Express',
  max_temp: 'Max Temperature',
  integrated_gpu: 'Integrated GPU',
  maks_p: 'Recommended PSU',
  memory_bandwidth: 'Memory Bandwidth',
  cuda_cores: 'CUDA Cores',
  ray_tracing_cores: 'RT Cores',
  tensor_cores: 'Tensor Cores',
  max_resolution: 'Max Resolution',
  directx: 'DirectX',
  opengl: 'OpenGL',
  width: 'Width',
  material: 'Material',
  bearing: 'Bearing',
  fan_connector: 'Fan Connector',
  airflow: 'Airflow',
  architecture: 'Architecture',
  l2_cache: 'L2 Cache',
  l3_cache: 'L3 Cache',
  max_memory: 'Max Memory',
  memory_channels: 'Memory Channels'
};

export function getSpecName(key) {
  return SPEC_NAMES[key] || key;
}

export function getSpecNameDetail(key) {
  return SPEC_NAMES_DETAIL[key] || key;
}
