const SPEC_NAMES = {
  oc: 'Операционная система',
  cover: 'Корпус',
  cpu: 'Процессор',
  gpu: 'Видеокарта',
  ram: 'Оперативная память',
  storage: 'Накопитель',
  psu: 'Блок питания',
  cooling: 'Охлаждение',
  memory: 'Тип памяти',
  interface: 'Видеоразъемы',
  ports: 'Максимальное разрешение',
  maks_p: 'Рекомендуемый блок питания',
  maks: 'Рекомендуемый блок питания',
  power: 'Энергопотребление',
  sensor: 'Сенсор',
  buttons: 'Кнопки',
  connection: 'Подключение',
  battery: 'Батарея',
  interface_p: 'Интерфейс подключения',
  weight: 'Вес',
  driver: 'Драйвер',
  frequency: 'Частота',
  microphone: 'Микрофон',
  cable: 'Кабель',
  capacity: 'Емкость',
  type: 'Тип',
  cas: 'CAS Latency',
  voltage: 'Напряжение',
  rgb: 'RGB подсветка',
  switches: 'Переключатели',
  backlight: 'Подсветка',
  anticost: 'Анти-ост',
  diagonal: 'Диагональ',
  resolution: 'Разрешение',
  panel: 'Матрица',
  refresh: 'Частота обновления',
  response: 'Время отклика',
  surface: 'Поверхность',
  size: 'Размер',
  base: 'Основание',
  cleaning: 'Чистка',
  compatibility: 'Совместимость',
  rpm: 'Скорость вращения',
  cache: 'Кэш',
  formfactor: 'Форм-фактор',
  warranty: 'Гарантия',
  certificate: 'Сертификат',
  pfc: 'PFC',
  cables: 'Кабели',
  protection: 'Защита',
  cores: 'Ядра',
  threads: 'Потоки',
  turbo: 'Турбо частота',
  socket: 'Сокет',
  tdp: 'TDP',
  heatpipes: 'Тепловые трубки',
  fan: 'Вентилятор',
  noise: 'Уровень шума',
  manufacturer: 'Производитель',
  country: 'Страна производства',
  chipset: 'Чипсет',
  formfactor_mb: 'Форм-фактор материнской платы',
  ram_installed: 'Количество установленных модулей',
  ram_total: 'Общий объем оперативной памяти',
  ram_frequency: 'Частота оперативной памяти',
  timings: 'Тайминги',
  profile: 'Профиль',
  height: 'Высота модуля',
  heat_spreader: 'Радиатор',
  gpu_memory: 'Объем видеопамяти',
  memory_type: 'Тип видеопамяти',
  clock_base: 'Базовая частота GPU',
  clock_boost: 'Частота разгона GPU',
  length: 'Длина видеокарты',
  slots: 'Занимаемых слотов',
  storage_type: 'Тип накопителя',
  storage_interface: 'Интерфейс подключения',
  storage_speed: 'Скорость чтения',
  efficiency: 'КПД',
  fan_speed: 'Скорость вентилятора',
  depth: 'Глубина',
  cooling_type: 'Тип охлаждения',
  case: 'Корпус',
  case_rgb: 'Подсветка корпуса',
  case_fans: 'Вентиляторы',
  polling: 'Частота опроса',
  battery_type: 'Тип батареи',
  surround: 'Объемный звук',
  impedance: 'Импеданс',
  sensitivity: 'Чувствительность',
  mic_frequency: 'Частотный диапазон микрофона',
  keys: 'Количество клавиш',
  wrist_rest: 'Подставка для рук',
  thickness: 'Толщина',
  brightness: 'Яркость',
  contrast: 'Контрастность',
  color: 'Цветовой охват',
  hdr: 'HDR',
  vesa: 'VESA крепление',
  socket_cpu: 'Сокет процессора',
  lithography: 'Технологический процесс',
  memory_support: 'Поддержка памяти',
  pci_express: 'PCI Express',
  max_temp: 'Максимальная температура',
  integrated_gpu: 'Встроенная графика',
  memory_bandwidth: 'Пропускная способность памяти',
  cuda_cores: 'CUDA ядра',
  ray_tracing_cores: 'RT ядра',
  tensor_cores: 'Tensor ядра',
  max_resolution: 'Максимальное разрешение',
  directx: 'DirectX',
  opengl: 'OpenGL',
  width: 'Ширина',
  material: 'Материал',
  bearing: 'Тип подшипника',
  fan_connector: 'Разъём вентилятора',
  airflow: 'Воздушный поток',
  architecture: 'Архитектура',
  l2_cache: 'Кэш L2',
  l3_cache: 'Кэш L3',
  max_memory: 'Максимальный объём памяти',
  memory_channels: 'Каналы памяти'
};

const SPEC_NAMES_DETAIL = {
  warranty: 'Гарантия от производителя',
  manufacturer: 'Производитель',
  country: 'Страна производства',
  oc: 'Операционная система',
  cpu: 'Модель процессора',
  buttons: 'Количество ядер процессора',
  threads: 'Количество потоков',
  frequency: 'Частота процессора',
  anticost: 'Автоматическое увеличение частоты',
  socket_cpu: 'Сокет процессора',
  cache: 'Кэш процессора',
  cover: 'Сокет',
  chipset: 'Чипсет',
  ram: 'Общее количество слотов оперативной памяти',
  formfactor_mb: 'Форм-фактор материнской платы',
  memory: 'Тип оперативной памяти',
  formfactor: 'Формат оперативной памяти',
  ram_installed: 'Количество установленных модулей',
  ram_total: 'Общий объем оперативной памяти',
  ram_frequency: 'Частота оперативной памяти',
  cas: 'CAS Latency',
  voltage: 'Напряжение',
  rgb: 'RGB подсветка',
  capacity: 'Емкость',
  timings: 'Тайминги',
  profile: 'Профиль',
  height: 'Высота модуля',
  heat_spreader: 'Радиатор',
  gpu: 'Модель дискретной видеокарты',
  type: 'Тип видеокарты',
  gpu_memory: 'Объем видеопамяти',
  interface: 'Видеоразъемы',
  memory_type: 'Тип видеопамяти',
  ports: 'Максимальное разрешение',
  power: 'Энергопотребление',
  clock_base: 'Базовая частота GPU',
  clock_boost: 'Частота разгона GPU',
  length: 'Длина видеокарты',
  slots: 'Занимаемых слотов',
  storage: 'Накопитель',
  storage_type: 'Тип накопителя',
  storage_interface: 'Интерфейс подключения',
  storage_speed: 'Скорость чтения',
  rpm: 'Скорость вращения',
  noise: 'Уровень шума',
  psu: 'Мощность блока питания',
  certificate: 'Сертификат',
  pfc: 'PFC',
  cables: 'Тип кабелей',
  protection: 'Защита',
  efficiency: 'КПД',
  fan_speed: 'Скорость вентилятора',
  depth: 'Глубина',
  cooling: 'Охлаждение',
  cooling_type: 'Тип охлаждения',
  case: 'Корпус',
  case_rgb: 'Подсветка корпуса',
  case_fans: 'Вентиляторы',
  sensor: 'Сенсор',
  connection: 'Подключение',
  battery: 'Батарея',
  weight: 'Вес',
  interface_p: 'Интерфейс подключения',
  polling: 'Частота опроса',
  switches: 'Переключатели',
  battery_type: 'Тип батареи',
  driver: 'Драйвер',
  microphone: 'Микрофон',
  cable: 'Кабель',
  surround: 'Объемный звук',
  impedance: 'Импеданс',
  sensitivity: 'Чувствительность',
  mic_frequency: 'Частотный диапазон микрофона',
  backlight: 'Подсветка',
  keys: 'Количество клавиш',
  wrist_rest: 'Подставка для рук',
  surface: 'Поверхность',
  size: 'Размер',
  base: 'Основание',
  cleaning: 'Чистка',
  compatibility: 'Совместимость',
  thickness: 'Толщина',
  diagonal: 'Диагональ',
  resolution: 'Разрешение',
  panel: 'Матрица',
  refresh: 'Частота обновления',
  response: 'Время отклика',
  brightness: 'Яркость',
  contrast: 'Контрастность',
  color: 'Цветовой охват',
  hdr: 'HDR',
  vesa: 'VESA крепление',
  cores: 'Количество ядер',
  turbo: 'Турбо частота',
  socket: 'Сокет',
  tdp: 'TDP',
  heatpipes: 'Тепловые трубки',
  fan: 'Вентилятор',
  lithography: 'Технологический процесс',
  memory_support: 'Поддержка памяти',
  pci_express: 'PCI Express',
  max_temp: 'Максимальная температура',
  integrated_gpu: 'Встроенная графика',
  maks_p: 'Рекомендуемый блок питания',
  memory_bandwidth: 'Пропускная способность памяти',
  cuda_cores: 'CUDA ядра',
  ray_tracing_cores: 'RT ядра',
  tensor_cores: 'Tensor ядра',
  max_resolution: 'Максимальное разрешение',
  directx: 'DirectX',
  opengl: 'OpenGL',
  width: 'Ширина',
  material: 'Материал',
  bearing: 'Тип подшипника',
  fan_connector: 'Разъём вентилятора',
  airflow: 'Воздушный поток',
  architecture: 'Архитектура',
  l2_cache: 'Кэш L2',
  l3_cache: 'Кэш L3',
  max_memory: 'Максимальный объём памяти',
  memory_channels: 'Каналы памяти'
};

export function getSpecName(key) {
  return SPEC_NAMES[key] || key;
}

export function getSpecNameDetail(key) {
  return SPEC_NAMES_DETAIL[key] || key;
}
