export const detailedSpecs = {
  '1': {
    warranty: '24 мес.',
    manufacturer: 'ZET GAMING',
    country: 'Китай',
    oc: 'без ОС',
    cpu: 'Core i5-12400F',
    buttons: '6',
    threads: '12',
    frequency: '2.5 ГГц',
    anticost: '4.4 ГГц',
    socket_cpu: 'LGA1700',
    cache: '18 МБ',
    cover: 'LGA1700',
    chipset: 'Intel B660',
    ram: '4',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2',
    ram_total: '16 ГБ',
    ram_frequency: '3200 МГц',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Да',
    gpu: 'GeForce RTX 3060Ti',
    type: 'дискретная',
    gpu_memory: '8 ГБ',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '200 Вт',
    storage: '512GB M.2 NVMe',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3500 МБ/с',
    psu: '650W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Полумодульный',
    protection: 'OVP, UVP, SCP',
    cooling: 'Жидкостное охлаждение',
    cooling_type: 'СВО 240мм',
    case: 'DEEPCOOL MATREXX 55 MESH',
    case_rgb: 'ADD-RGB 4F',
    case_fans: '4 вентилятора'
  },
  
  '2': {
    warranty: '36 мес.',
    manufacturer: 'Palit',
    country: 'Тайвань',
    gpu: 'GeForce RTX 3080',
    type: 'дискретная',
    gpu_memory: '10 ГБ',
    interface: 'DisplayPort x3, HDMI',
    memory_type: 'GDDR6X',
    ports: '7680x4320',
    power: '320 Вт',
    cooling: 'GamingPro 3 вентилятора',
    cooling_type: 'Воздушное',
    interface_p: 'PCI-E 4.0',
    clock_base: '1440 МГц',
    clock_boost: '1710 МГц',
    length: '299 мм',
    slots: '2.7 слота'
  },

  '3': {
    warranty: '24 мес.',
    manufacturer: 'Razer',
    country: 'Китай',
    sensor: 'Оптический 16000 DPI',
    buttons: '8',
    connection: 'USB / Беспроводная',
    battery: 'До 70 часов',
    weight: '89 грамм',
    type: 'Игровая мышь',
    interface_p: 'USB 2.0',
    cable: '1.8 метра',
    rgb: 'Да',
    polling: '1000 Гц',
    switches: 'Механические',
    battery_type: 'AA батарейка'
  },

  '4': {
    warranty: '12 мес.',
    manufacturer: 'Sven',
    country: 'Китай',
    type: 'Игровые наушники',
    driver: '50mm динамики',
    frequency: '20Hz - 20kHz',
    microphone: 'Съемный с шумоподавлением',
    connection: 'USB / 3.5mm',
    cable: '2 метра',
    weight: '320 грамм',
    rgb: 'Да',
    surround: '7.1 виртуальный',
    impedance: '32 Ом',
    sensitivity: '105 дБ',
    mic_frequency: '100Hz - 10kHz'
  },

  '5': {
    warranty: '24 мес.',
    manufacturer: 'Custom Build',
    country: 'Китай',
    oc: 'без ОС',
    cpu: 'Core i5-13400F',
    buttons: '10',
    threads: '16',
    frequency: '2.5 ГГц',
    anticost: '4.6 ГГц',
    socket_cpu: 'LGA1700',
    cache: '20 МБ',
    cover: 'LGA1700',
    chipset: 'Intel B660',
    ram: '4',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2',
    ram_total: '16 ГБ',
    ram_frequency: '3200 МГц',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Нет',
    gpu: 'NVIDIA RTX 4060Ti',
    type: 'дискретная',
    gpu_memory: '8 ГБ',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '160 Вт',
    storage: '512GB NVMe SSD',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3000 МБ/с',
    psu: '600W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Стандартные',
    protection: 'OVP, UVP, SCP',
    cooling: 'Башенный кулер',
    cooling_type: 'Воздушное',
    case: 'Zalman N4',
    case_rgb: 'Нет',
    case_fans: '2 вентилятора'
  },

  '6': {
    warranty: '24 мес.',
    manufacturer: 'Custom Build',
    country: 'Китай',
    oc: 'без ОС',
    cpu: 'AMD Ryzen 5 5600',
    buttons: '6',
    threads: '12',
    frequency: '3.5 ГГц',
    anticost: '4.4 ГГц',
    socket_cpu: 'AM4',
    cache: '32 МБ',
    cover: 'AM4',
    chipset: 'AMD B550',
    ram: '4',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2',
    ram_total: '16 ГБ',
    ram_frequency: '3200 МГц',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Да',
    gpu: 'NVIDIA GTX 1660 Super',
    type: 'дискретная',
    gpu_memory: '6 ГБ',
    interface: 'DisplayPort, HDMI, DVI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '125 Вт',
    storage: '512GB SATA SSD',
    storage_type: 'SSD',
    storage_interface: 'SATA III',
    storage_speed: '560 МБ/с',
    psu: '550W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Стандартные',
    protection: 'OVP, UVP',
    cooling: 'Воздушное охлаждение',
    cooling_type: 'Башенный кулер',
    case: 'DEEPCOOL MATREXX 70',
    case_rgb: 'ADD-RGB',
    case_fans: '3 вентилятора'
  },

  '7': {
    warranty: '36 мес.',
    manufacturer: 'Kingston',
    country: 'Тайвань',
    type: 'DDR4',
    capacity: '16GB (2x8GB)',
    memory: 'DDR4',
    formfactor: 'DIMM',
    frequency: '2400 МГц',
    cas: 'CL15',
    voltage: '1.2V',
    rgb: 'Да',
    timings: '15-15-15-35',
    profile: 'XMP 2.0',
    height: '42 мм',
    heat_spreader: 'Алюминиевый'
  },

  '8': {
    warranty: '24 мес.',
    manufacturer: 'Razer',
    country: 'Китай',
    type: 'Механическая клавиатура',
    switches: 'Razer Green',
    backlight: 'RGB Chroma',
    anticost: 'N-Key Rollover',
    connection: 'USB',
    cable: 'Отсоединяемый',
    ports: 'USB pass-through',
    keys: '104 клавиши',
    polling: '1000 Гц',
    weight: '1310 грамм',
    wrist_rest: 'Съемная'
  },

  '9': {
    warranty: '36 мес.',
    manufacturer: 'BenQ',
    country: 'Тайвань',
    type: 'Монитор',
    diagonal: '27 дюймов',
    resolution: '2560x1440',
    panel: 'IPS',
    refresh: '144 Гц',
    response: '5 мс',
    ports: 'HDMI, DisplayPort, USB-C',
    brightness: '350 кд/м²',
    contrast: '1000:1',
    color: '99% sRGB',
    hdr: 'Нет',
    vesa: '100x100 мм'
  },

  '10': {
    warranty: '24 мес.',
    manufacturer: 'Logitech',
    country: 'Китай',
    type: 'Коврик для мыши',
    surface: 'Жесткая полимерная',
    size: '340 x 280 x 3 мм',
    base: 'Резиновое основание',
    cleaning: 'Легко чистится',
    compatibility: 'Все типы сенсоров',
    thickness: '3 мм',
    weight: '215 грамм'
  },

  '11': {
    warranty: '24 мес.',
    manufacturer: 'Western Digital',
    country: 'Таиланд',
    type: 'HDD',
    capacity: '1TB',
    storage_interface: 'SATA III 6 Gb/s',
    rpm: '7200 RPM',
    cache: '64MB',
    formfactor: '3.5 дюйма',
    storage_speed: '150 МБ/с',
    power: '6.8 Вт',
    noise: '29 дБ'
  },

  '12': {
    warranty: '24 мес.',
    manufacturer: 'Gamemax',
    country: 'Китай',
    type: 'Блок питания',
    power: '850W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cooling: '120mm RGB вентилятор',
    cables: 'Полумодульные',
    protection: 'OVP, UVP, SCP, OPP, OCP',
    efficiency: '85%',
    fan_speed: '800-1800 RPM',
    formfactor: 'ATX',
    depth: '140 мм'
  },

  '13': {
    warranty: '36 мес.',
    manufacturer: 'Intel',
    country: 'Малайзия',
    type: 'Процессор',
    cpu: 'Core i5-12400F',
    cores: '6',
    threads: '12',
    frequency: '2.5 ГГц',
    anticost: '4.4 ГГц',
    socket_cpu: 'LGA1700',
    cache: '18 МБ',
    tdp: '65 Вт',
    lithography: '10 нм',
    memory_support: 'DDR4-3200, DDR5-4800',
    pci_express: 'PCIe 5.0, PCIe 4.0',
    max_temp: '100°C',
    integrated_gpu: 'Нет'
  },

  '14': {
    warranty: '24 мес.',
    manufacturer: 'DEEPCOOL',
    country: 'Китай',
    type: 'Кулер для процессора',
    cooling_type: 'Башенный',
    heatpipes: '4 тепловые трубки',
    fan: '120mm PWM',
    rpm: '500-2000 RPM',
    noise: '29.4 дБ',
    compatibility: 'LGA1700, LGA1200, AM4, AM5',
    tdp: '220 Вт',
    height: '155 мм',
    weight: '610 грамм',
    rgb: 'Нет',
    material: 'Алюминий + медь',
    bearing: 'Гидродинамический'
  },

  'gpu-1': {
    warranty: '36 мес.',
    manufacturer: 'Palit',
    country: 'Тайвань',
    gpu: 'GeForce RTX 3080',
    type: 'дискретная',
    gpu_memory: '10 ГБ',
    interface: 'DisplayPort x3, HDMI',
    memory_type: 'GDDR6X',
    ports: '7680x4320',
    power: '320 Вт',
    cooling: 'GamingPro 3 вентилятора',
    cooling_type: 'Воздушное',
    interface_p: 'PCI-E 4.0',
    clock_base: '1440 МГц',
    clock_boost: '1710 МГц',
    length: '299 мм',
    slots: '2.7 слота',
    memory_bandwidth: '760 ГБ/с',
    cuda_cores: '8704',
    ray_tracing_cores: '68 RT ядер',
    tensor_cores: '272 Tensor ядра',
    max_resolution: '7680x4320 @ 60Hz',
    directx: 'DirectX 12 Ultimate',
    opengl: 'OpenGL 4.6'
  },

  'cpu-1': {
    warranty: '36 мес.',
    manufacturer: 'Intel',
    country: 'Малайзия',
    type: 'Процессор',
    cpu: 'Core i5-12400F',
    cores: '6',
    threads: '12',
    frequency: '2.5 ГГц',
    anticost: '4.4 ГГц',
    socket_cpu: 'LGA1700',
    cache: '18 МБ',
    tdp: '65 Вт',
    lithography: '10 нм',
    memory_support: 'DDR4-3200, DDR5-4800',
    pci_express: 'PCIe 5.0, PCIe 4.0',
    max_temp: '100°C',
    integrated_gpu: 'Нет',
    architecture: 'Alder Lake',
    l2_cache: '7.5 МБ',
    l3_cache: '18 МБ',
    max_memory: '128 ГБ',
    memory_channels: '2'
  },

  'cooler-1': {
    warranty: '24 мес.',
    manufacturer: 'DEEPCOOL',
    country: 'Китай',
    type: 'Кулер для процессора',
    cooling_type: 'Башенный',
    heatpipes: '4 тепловые трубки',
    fan: '120mm PWM',
    rpm: '900-1600 RPM',
    noise: '27 дБ',
    compatibility: 'LGA1700, LGA1200, LGA1151, AM4, AM5',
    tdp: '220 Вт',
    height: '155 мм',
    width: '127 мм',
    depth: '97 мм',
    weight: '610 грамм',
    rgb: 'Нет',
    material: 'Алюминиевые пластины + медные трубки',
    bearing: 'Гидродинамический',
    fan_connector: '4-pin PWM',
    airflow: '64.5 CFM'
  },

  'build-1': {
    warranty: '24 мес.',
    manufacturer: 'ZET GAMING',
    country: 'Китай',
    oc: 'без ОС',
    cpu: 'Core i5-12400F',
    cores: '6',
    threads: '12',
    frequency: '2.5 ГГц',
    anticost: '4.4 ГГц',
    socket_cpu: 'LGA1700',
    cache: '18 МБ',
    cover: 'DEEPCOOL MATREXX 55 MESH',
    chipset: 'Intel B660',
    ram: '4 слота',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2 планки',
    ram_total: '16 ГБ',
    ram_frequency: '3200 МГц',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Да',
    gpu: 'GeForce RTX 3060Ti',
    type: 'дискретная',
    gpu_memory: '8 ГБ',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '200 Вт',
    storage: '512GB M.2 NVMe',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3500 МБ/с',
    psu: '650W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Полумодульный',
    protection: 'OVP, UVP, SCP',
    cooling: 'Жидкостное охлаждение',
    cooling_type: 'СВО 240мм',
    case: 'DEEPCOOL MATREXX 55 MESH',
    case_rgb: 'ADD-RGB 4F',
    case_fans: '4 вентилятора'
  },

  'build-2': {
    warranty: '24 мес.',
    manufacturer: 'Custom Build',
    country: 'Китай',
    oc: 'без ОС',
    cpu: 'Core i5-13400F',
    cores: '10',
    threads: '16',
    frequency: '2.5 ГГц',
    anticost: '4.6 ГГц',
    socket_cpu: 'LGA1700',
    cache: '20 МБ',
    cover: 'Zalman N4',
    chipset: 'Intel B660',
    ram: '4 слота',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2 планки',
    ram_total: '16 ГБ',
    ram_frequency: '3200 МГц',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Нет',
    gpu: 'NVIDIA RTX 4060Ti',
    type: 'дискретная',
    gpu_memory: '8 ГБ',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '160 Вт',
    storage: '512GB NVMe SSD',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3000 МБ/с',
    psu: '600W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Стандартные',
    protection: 'OVP, UVP, SCP',
    cooling: 'Башенный кулер',
    cooling_type: 'Воздушное',
    case: 'Zalman N4',
    case_rgb: 'Нет',
    case_fans: '2 вентилятора'
  },

  'build-3': {
    warranty: '24 мес.',
    manufacturer: 'Custom Build',
    country: 'Китай',
    oc: 'без ОС',
    cpu: 'AMD Ryzen 5 5600',
    cores: '6',
    threads: '12',
    frequency: '3.5 ГГц',
    anticost: '4.4 ГГц',
    socket_cpu: 'AM4',
    cache: '32 МБ',
    cover: 'DEEPCOOL MATREXX 70',
    chipset: 'AMD B550',
    ram: '4 слота',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2 планки',
    ram_total: '16 ГБ',
    ram_frequency: '3200 МГц',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Да',
    gpu: 'NVIDIA GTX 1660 Super',
    type: 'дискретная',
    gpu_memory: '6 ГБ',
    interface: 'DisplayPort, HDMI, DVI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '125 Вт',
    storage: '512GB SATA SSD',
    storage_type: 'SSD',
    storage_interface: 'SATA III',
    storage_speed: '560 МБ/с',
    psu: '550W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Стандартные',
    protection: 'OVP, UVP',
    cooling: 'Воздушное охлаждение',
    cooling_type: 'Башенный кулер',
    case: 'DEEPCOOL MATREXX 70',
    case_rgb: 'ADD-RGB',
    case_fans: '3 вентилятора'
  }
};