export const detailedSpecs = {
  '1': {
    warranty: '24 mos.',
    manufacturer: 'ZET GAMING',
    country: 'China',
    oc: 'No OS',
    cpu: 'Core i5-12400F',
    buttons: '6',
    threads: '12',
    frequency: '2.5 GHz',
    anticost: '4.4 GHz',
    socket_cpu: 'LGA1700',
    cache: '18 MB',
    cover: 'LGA1700',
    chipset: 'Intel B660',
    ram: '4',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2',
    ram_total: '16 GB',
    ram_frequency: '3200 MHz',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Yes',
    gpu: 'GeForce RTX 3060Ti',
    type: 'discrete',
    gpu_memory: '8 GB',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '200 W',
    storage: '512GB M.2 NVMe',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3500 MB/s',
    psu: '650W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Semi-modular',
    protection: 'OVP, UVP, SCP',
    cooling: 'Liquid cooling',
    cooling_type: 'AIO 240mm',
    case: 'DEEPCOOL MATREXX 55 MESH',
    case_rgb: 'ADD-RGB 4F',
    case_fans: '4 fans'
  },
  
  '2': {
    warranty: '36 mos.',
    manufacturer: 'Palit',
    country: 'Taiwan',
    gpu: 'GeForce RTX 3080',
    type: 'discrete',
    gpu_memory: '10 GB',
    interface: 'DisplayPort x3, HDMI',
    memory_type: 'GDDR6X',
    ports: '7680x4320',
    power: '320 Вт',
    cooling: 'GamingPro 3 fans',
    cooling_type: 'Air',
    interface_p: 'PCI-E 4.0',
    clock_base: '1440 MHz',
    clock_boost: '1710 MHz',
    length: '299 mm',
    slots: '2.7 slots'
  },

  '3': {
    warranty: '24 mos.',
    manufacturer: 'Razer',
    country: 'China',
    sensor: 'Optical 16000 DPI',
    buttons: '8',
    connection: 'USB / Wireless',
    battery: 'Up to 70 hours',
    weight: '89 g',
    type: 'Gaming mouse',
    interface_p: 'USB 2.0',
    cable: '1.8 m',
    rgb: 'Yes',
    polling: '1000 Hz',
    switches: 'Mechanical',
    battery_type: 'AA battery'
  },

  '4': {
    warranty: '12 mos.',
    manufacturer: 'Sven',
    country: 'China',
    type: 'Gaming headphones',
    driver: '50mm drivers',
    frequency: '20Hz - 20kHz',
    microphone: 'Съемный с шумоподавлением',
    connection: 'USB / 3.5mm',
    cable: '2 m',
    weight: '320 g',
    rgb: 'Yes',
    surround: '7.1 virtual',
    impedance: '32 Ohm',
    sensitivity: '105 дБ',
    mic_frequency: '100Hz - 10kHz'
  },

  '5': {
    warranty: '24 mos.',
    manufacturer: 'Custom Build',
    country: 'China',
    oc: 'No OS',
    cpu: 'Core i5-13400F',
    buttons: '10',
    threads: '16',
    frequency: '2.5 GHz',
    anticost: '4.6 GHz',
    socket_cpu: 'LGA1700',
    cache: '20 MB',
    cover: 'LGA1700',
    chipset: 'Intel B660',
    ram: '4',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2',
    ram_total: '16 GB',
    ram_frequency: '3200 MHz',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'No',
    gpu: 'NVIDIA RTX 4060Ti',
    type: 'discrete',
    gpu_memory: '8 GB',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '160 W',
    storage: '512GB NVMe SSD',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3000 MB/s',
    psu: '600W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Standard',
    protection: 'OVP, UVP, SCP',
    cooling: 'Tower cooler',
    cooling_type: 'Air',
    case: 'Zalman N4',
    case_rgb: 'No',
    case_fans: '2 fans'
  },

  '6': {
    warranty: '24 mos.',
    manufacturer: 'Custom Build',
    country: 'China',
    oc: 'No OS',
    cpu: 'AMD Ryzen 5 5600',
    buttons: '6',
    threads: '12',
    frequency: '3.5 GHz',
    anticost: '4.4 GHz',
    socket_cpu: 'AM4',
    cache: '32 MB',
    cover: 'AM4',
    chipset: 'AMD B550',
    ram: '4',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2',
    ram_total: '16 GB',
    ram_frequency: '3200 MHz',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Yes',
    gpu: 'NVIDIA GTX 1660 Super',
    type: 'discrete',
    gpu_memory: '6 ГБ',
    interface: 'DisplayPort, HDMI, DVI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '125 W',
    storage: '512GB SATA SSD',
    storage_type: 'SSD',
    storage_interface: 'SATA III',
    storage_speed: '560 MB/s',
    psu: '550W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Standard',
    protection: 'OVP, UVP',
    cooling: 'Air cooling',
    cooling_type: 'Tower cooler',
    case: 'DEEPCOOL MATREXX 70',
    case_rgb: 'ADD-RGB',
    case_fans: '3 fans'
  },

  '7': {
    warranty: '36 mos.',
    manufacturer: 'Kingston',
    country: 'Taiwan',
    type: 'DDR4',
    capacity: '16GB (2x8GB)',
    memory: 'DDR4',
    formfactor: 'DIMM',
    frequency: '2400 MHz',
    cas: 'CL15',
    voltage: '1.2V',
    rgb: 'Yes',
    timings: '15-15-15-35',
    profile: 'XMP 2.0',
    height: '42 mm',
    heat_spreader: 'Aluminum'
  },

  '8': {
    warranty: '24 mos.',
    manufacturer: 'Razer',
    country: 'China',
    type: 'Mechanical keyboard',
    switches: 'Razer Green',
    backlight: 'RGB Chroma',
    anticost: 'N-Key Rollover',
    connection: 'USB',
    cable: 'Отсоединяемый',
    ports: 'USB pass-through',
    keys: '104 keys',
    polling: '1000 Hz',
    weight: '1310 g',
    wrist_rest: 'Detachable'
  },

  '9': {
    warranty: '36 mos.',
    manufacturer: 'BenQ',
    country: 'Taiwan',
    type: 'Monitor',
    diagonal: '27 inch',
    resolution: '2560x1440',
    panel: 'IPS',
    refresh: '144 Hz',
    response: '5 ms',
    ports: 'HDMI, DisplayPort, USB-C',
    brightness: '350 кд/м²',
    contrast: '1000:1',
    color: '99% sRGB',
    hdr: 'No',
    vesa: '100x100 mm'
  },

  '10': {
    warranty: '24 mos.',
    manufacturer: 'Logitech',
    country: 'China',
    type: 'Mouse pad',
    surface: 'Hard polymer',
    size: '340 x 280 x 3 mm',
    base: 'Rubber base',
    cleaning: 'Easy to clean',
    compatibility: 'Все типы сенсоров',
    thickness: '3 mm',
    weight: '215 g'
  },

  '11': {
    warranty: '24 mos.',
    manufacturer: 'Western Digital',
    country: 'Thailand',
    type: 'HDD',
    capacity: '1TB',
    storage_interface: 'SATA III 6 Gb/s',
    rpm: '7200 RPM',
    cache: '64MB',
    formfactor: '3.5 inch',
    storage_speed: '150 MB/s',
    power: '6.8 W',
    noise: '29 дБ'
  },

  '12': {
    warranty: '24 mos.',
    manufacturer: 'Gamemax',
    country: 'China',
    type: 'Power supply',
    power: '850W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cooling: '120mm RGB вентилятор',
    cables: 'Полумодульные',
    protection: 'OVP, UVP, SCP, OPP, OCP',
    efficiency: '85%',
    fan_speed: '800-1800 RPM',
    formfactor: 'ATX',
    depth: '140 mm'
  },

  '13': {
    warranty: '36 mos.',
    manufacturer: 'Intel',
    country: 'Malaysia',
    type: 'Processor',
    cpu: 'Core i5-12400F',
    cores: '6',
    threads: '12',
    frequency: '2.5 GHz',
    anticost: '4.4 GHz',
    socket_cpu: 'LGA1700',
    cache: '18 MB',
    tdp: '65 W',
    lithography: '10 nm',
    memory_support: 'DDR4-3200, DDR5-4800',
    pci_express: 'PCIe 5.0, PCIe 4.0',
    max_temp: '100°C',
    integrated_gpu: 'No'
  },

  '14': {
    warranty: '24 mos.',
    manufacturer: 'DEEPCOOL',
    country: 'China',
    type: 'CPU cooler',
    cooling_type: 'Tower',
    heatpipes: '4 heat pipes',
    fan: '120mm PWM',
    rpm: '500-2000 RPM',
    noise: '29.4 дБ',
    compatibility: 'LGA1700, LGA1200, AM4, AM5',
    tdp: '220 Вт',
    height: '155 mm',
    weight: '610 g',
    rgb: 'No',
    material: 'Алюминий + copper',
    bearing: 'Hydrodynamic'
  },

  'gpu-1': {
    warranty: '36 mos.',
    manufacturer: 'Palit',
    country: 'Taiwan',
    gpu: 'GeForce RTX 3080',
    type: 'discrete',
    gpu_memory: '10 GB',
    interface: 'DisplayPort x3, HDMI',
    memory_type: 'GDDR6X',
    ports: '7680x4320',
    power: '320 Вт',
    cooling: 'GamingPro 3 fans',
    cooling_type: 'Air',
    interface_p: 'PCI-E 4.0',
    clock_base: '1440 MHz',
    clock_boost: '1710 MHz',
    length: '299 mm',
    slots: '2.7 slots',
    memory_bandwidth: '760 GB/s',
    cuda_cores: '8704',
    ray_tracing_cores: '68 RT cores',
    tensor_cores: '272 Tensor ядра',
    max_resolution: '7680x4320 @ 60Hz',
    directx: 'DirectX 12 Ultimate',
    opengl: 'OpenGL 4.6'
  },

  'cpu-1': {
    warranty: '36 mos.',
    manufacturer: 'Intel',
    country: 'Malaysia',
    type: 'Processor',
    cpu: 'Core i5-12400F',
    cores: '6',
    threads: '12',
    frequency: '2.5 GHz',
    anticost: '4.4 GHz',
    socket_cpu: 'LGA1700',
    cache: '18 MB',
    tdp: '65 W',
    lithography: '10 nm',
    memory_support: 'DDR4-3200, DDR5-4800',
    pci_express: 'PCIe 5.0, PCIe 4.0',
    max_temp: '100°C',
    integrated_gpu: 'No',
    architecture: 'Alder Lake',
    l2_cache: '7.5 MB',
    l3_cache: '18 MB',
    max_memory: '128 GB',
    memory_channels: '2'
  },

  'cooler-1': {
    warranty: '24 mos.',
    manufacturer: 'DEEPCOOL',
    country: 'China',
    type: 'CPU cooler',
    cooling_type: 'Tower',
    heatpipes: '4 heat pipes',
    fan: '120mm PWM',
    rpm: '900-1600 RPM',
    noise: '27 дБ',
    compatibility: 'LGA1700, LGA1200, LGA1151, AM4, AM5',
    tdp: '220 Вт',
    height: '155 mm',
    width: '127 mm',
    depth: '97 mm',
    weight: '610 g',
    rgb: 'No',
    material: 'Алюминиевые пластины + copper трубки',
    bearing: 'Hydrodynamic',
    fan_connector: '4-pin PWM',
    airflow: '64.5 CFM'
  },

  'build-1': {
    warranty: '24 mos.',
    manufacturer: 'ZET GAMING',
    country: 'China',
    oc: 'No OS',
    cpu: 'Core i5-12400F',
    cores: '6',
    threads: '12',
    frequency: '2.5 GHz',
    anticost: '4.4 GHz',
    socket_cpu: 'LGA1700',
    cache: '18 MB',
    cover: 'DEEPCOOL MATREXX 55 MESH',
    chipset: 'Intel B660',
    ram: '4 slots',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2 modules',
    ram_total: '16 GB',
    ram_frequency: '3200 MHz',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Yes',
    gpu: 'GeForce RTX 3060Ti',
    type: 'discrete',
    gpu_memory: '8 GB',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '200 W',
    storage: '512GB M.2 NVMe',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3500 MB/s',
    psu: '650W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Semi-modular',
    protection: 'OVP, UVP, SCP',
    cooling: 'Liquid cooling',
    cooling_type: 'AIO 240mm',
    case: 'DEEPCOOL MATREXX 55 MESH',
    case_rgb: 'ADD-RGB 4F',
    case_fans: '4 fans'
  },

  'build-2': {
    warranty: '24 mos.',
    manufacturer: 'Custom Build',
    country: 'China',
    oc: 'No OS',
    cpu: 'Core i5-13400F',
    cores: '10',
    threads: '16',
    frequency: '2.5 GHz',
    anticost: '4.6 GHz',
    socket_cpu: 'LGA1700',
    cache: '20 MB',
    cover: 'Zalman N4',
    chipset: 'Intel B660',
    ram: '4 slots',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2 modules',
    ram_total: '16 GB',
    ram_frequency: '3200 MHz',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'No',
    gpu: 'NVIDIA RTX 4060Ti',
    type: 'discrete',
    gpu_memory: '8 GB',
    interface: 'DisplayPort, HDMI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '160 W',
    storage: '512GB NVMe SSD',
    storage_type: 'SSD',
    storage_interface: 'M.2 (NVMe)',
    storage_speed: '3000 MB/s',
    psu: '600W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Standard',
    protection: 'OVP, UVP, SCP',
    cooling: 'Tower cooler',
    cooling_type: 'Air',
    case: 'Zalman N4',
    case_rgb: 'No',
    case_fans: '2 fans'
  },

  'build-3': {
    warranty: '24 mos.',
    manufacturer: 'Custom Build',
    country: 'China',
    oc: 'No OS',
    cpu: 'AMD Ryzen 5 5600',
    cores: '6',
    threads: '12',
    frequency: '3.5 GHz',
    anticost: '4.4 GHz',
    socket_cpu: 'AM4',
    cache: '32 MB',
    cover: 'DEEPCOOL MATREXX 70',
    chipset: 'AMD B550',
    ram: '4 slots',
    formfactor_mb: 'ATX',
    memory: 'DDR4',
    formfactor: 'DIMM',
    ram_installed: '2 modules',
    ram_total: '16 GB',
    ram_frequency: '3200 MHz',
    cas: 'CL16',
    voltage: '1.35V',
    rgb: 'Yes',
    gpu: 'NVIDIA GTX 1660 Super',
    type: 'discrete',
    gpu_memory: '6 ГБ',
    interface: 'DisplayPort, HDMI, DVI',
    memory_type: 'GDDR6',
    ports: '7680x4320',
    power: '125 W',
    storage: '512GB SATA SSD',
    storage_type: 'SSD',
    storage_interface: 'SATA III',
    storage_speed: '560 MB/s',
    psu: '550W',
    certificate: '80+ Bronze',
    pfc: 'Active PFC',
    cables: 'Standard',
    protection: 'OVP, UVP',
    cooling: 'Air cooling',
    cooling_type: 'Tower cooler',
    case: 'DEEPCOOL MATREXX 70',
    case_rgb: 'ADD-RGB',
    case_fans: '3 fans'
  }
};